### ISSUE TITLE
Сделать так, чтобы hover на кнопке не вылезал за пределы строки.

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#10]
Подсветка рассчитана на строки с иной высотой, а после уменьшения этой высоты — залезает на другие строки. 
<img width="283" alt="screen 2018-06-08 14 40 05" src="https://user-images.githubusercontent.com/3315944/41156286-ed1c6e54-6b29-11e8-85f6-d59116dd7bb8.png">

**Comment by vvzvlad** [comment]
Оценка: полтора часа, я смотрел уже этот таск, там верстка очень хитрая. после ресайза ховера нужны какие-то хаки, потому что элементы начинают перекрываться

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал фикс для всех кнопок в таблицах, которые нашёл. Залил в #50

**Comment by vvzvlad** [comment]
А их можно сделать в форме котя.. квадратиков?

**Comment by nismangulov** [comment]
@vvzvlad 

В форме котят тоже можно, но получится дольше. Чуть позже сделаю квадратики и напишу

**Comment by vvzvlad** [comment]
Тогда без котят, пусть будут квадратики.

**Comment by nismangulov** [comment]
@vvzvlad 

Убрал радиусы у ховера, теперь он стал квадратным

**Comment by vvzvlad** [comment]
еее, рок. Работает.

**Comment by vvzvlad** [comment]
Хотя нет, мое чувство прекрасного страдает. 
![image](https://user-images.githubusercontent.com/3315944/43195274-39fa4176-900d-11e8-9d81-a45920b93f18.png)

**Comment by nismangulov** [comment]
@vvzvlad 

Поправил высоту иконок, ховер сдвинулся выше - все стало ок

![image](https://user-images.githubusercontent.com/6184888/43242175-3e654f1c-90c1-11e8-9dd6-187c34fea594.png)

**Comment by vvzvlad** [comment]
В первой строке не до конца 
![image](https://user-images.githubusercontent.com/3315944/43395775-fef8f4ce-9407-11e8-8b2d-8931ffddf1a3.png)

**Comment by nismangulov** [comment]
@vvzvlad 

Не нашёл откуда берётся лишний пиксел в вёрстке, поэтому пришлось делать костыль на JS. Вроде работает, залил в https://github.com/vvzvlad/glue_web_app/pull/70

**Comment by vvzvlad** [comment]
Работает.
