### ISSUE TITLE
Окна редактирования в editor.vue

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#101]
При открытии скрипта в редакторе в заголовке показываются строки "Bus-event script "test"
Object "/glue/rps_o"". При нажатии на них должны появляться модальные окна редактирования названия и объекта(по образу rename-script-modal.vue). 
Редактирование object: scripts?action=update&uuid=this.uuid&object=new_object

**Comment by nismangulov** [comment]
@vvzvlad 

Залил в #104.

Сделал вызов двух модалок - по клику на название скрипта открывается модалка смены названия, а при клике на название объекта - открывается модалка смены названия объекта.

Ещё сделал хитрое обновление окна редактора - при удачном переименовании, имя и объект в редакторе меняются сразу, без перезагрузки страницы. Я думаю, так будет нагляднее.

**Comment by vvzvlad** [comment]
Да, круто, я не подумал об обновлении. Работает
