### ISSUE TITLE
Хранение адреса сервера и порта в localstorage

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#28]
В бранче devel-powpilot_ls имеется система смены адреса и порта сервера. В ней не работает сохранение данных в localstorage, надо починить. 

settings.vue — страница настройки. Функции находятся в main.js, :82 и дальше

**Comment by nismangulov** [comment]
@vvzvlad 

Починил работу с локалстораджем, теперь данные и читаются из него, и пишутся в него корректно.

**Comment by vvzvlad** [comment]
Да, запись-чтение работает.  
Только вот проблема: после записи другого порта/адреса скрипты, которые на других страницах получают значение через геттер, получают старое значение, то, которое было до записи. После перезагрузки страницы получают новое. Надо сделать так, чтобы изменения применялись сразу же.

**Comment by nismangulov** [comment]
@vvzvlad 

Ага, точно. Починил стор, теперь все корректно отображается и адреса применяются без перезагрузки страницы.

**Comment by vvzvlad** [comment]
Работает!
