### ISSUE TITLE
При скрытии меню содержимое остается такого же размера.

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#31]
Если скрыть меню, места станет больше, но содержимое не использует это место, а оставляет пустые поля. Сделать так, чтобы содержимое расширялось, занимая доступное место, а при разворачивании меню уменьшалось обратно. 
![image](https://user-images.githubusercontent.com/3315944/42318159-de346c92-8056-11e8-9cc9-58b6445b9e79.png)

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал верстку контейнера резиновой, теперь она тянется во всю доступную ширину

https://github.com/vvzvlad/glue_user_app/pull/49

**Comment by vvzvlad** [comment]
Работает!
