### ISSUE TITLE
Перевести все графики на D3.js

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#32]
В dashboard.vue и в waste/сontainers.vue есть графики, движок которых надо поменять на D3. 
В "Daily filling level" в сontainers это столбчатая диаграмма по дням за неделю, в остальных случаях пончиковые(пироговые без центра). У диаграмм должна быть легенда, созданная средствами D3 рядом, так, чтобы она визуально хорошо вмещалась в карточку(мне нравятся варианты с легендой в центре). 
График с легендой должен динамически занимать все пространство в карточке.

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал пончиковые (donut) диаграммы вместе c легендой. Диаграммы автоматически растягиваются под всю возможную ширину. Столбчатые постараюсь доделать завтра.

По поводу столбчатых есть вопрос - там должны быть столбики с группировкой по дням, как здесь, верно? https://bl.ocks.org/mbostock/3887051  
Или простой bar chart? https://bl.ocks.org/mbostock/3885304

https://github.com/vvzvlad/glue_user_app/pull/50

**Comment by vvzvlad** [comment]
Разъехалось как-то. ![image](https://user-images.githubusercontent.com/3315944/42507004-562eaf98-844c-11e8-9d88-676d18fee62b.png)

**Comment by vvzvlad** [comment]
>>По поводу столбчатых есть вопрос 
Простой bar chart

**Comment by nismangulov** [comment]
@vvzvlad 

> Разъехалось как-то. 

Ага, вижу. Верстка карточек была немного битой, теперь поправил - все ок.

Доработал donut chart - теперь респонзив работает корректно, шрифт легенды не уменьшается при ресайзе страницы. Ещё добавил bar chart с респонзивом.

Свежий пуллреквест здесь - https://github.com/vvzvlad/glue_user_app/pull/53

**Comment by vvzvlad** [comment]
И снова едет. 
![image](https://user-images.githubusercontent.com/3315944/42567637-091f57f8-8513-11e8-8c70-b2a0667d37ae.png)

![image](https://user-images.githubusercontent.com/3315944/42567641-0e296496-8513-11e8-9d14-7a9e7f159030.png)

**Comment by nismangulov** [comment]
@vvzvlad 

Добавил ещё немного хитрого респонзива https://github.com/vvzvlad/glue_user_app/pull/54

**Comment by vvzvlad** [comment]
Работает.
