### ISSUE TITLE
Высота строки в scripts/drivers

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#36]
В таблице, где значки есть в нескольких колонках не работает уменьшение высоты строки. Файл scripts_pages/components/files_table.vue

**Comment by nismangulov** [comment]
@vvzvlad 

Поправил, дело было в высоте кнопок.

Залил коммит в тот же пуллреквест https://github.com/vvzvlad/glue_web_app/pull/37

**Comment by vvzvlad** [comment]
работает.
