### ISSUE TITLE
Переместить кнопку выбора адреса сервера вбок. 

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#38]
![image](https://user-images.githubusercontent.com/3315944/42635722-7a08cc56-85ef-11e8-935d-e96e8790335d.png)
Надо перенести эту кнопку до конца вправо. Файл main_page.vue

**Comment by nismangulov** [comment]
@vvzvlad 

Перенес кнопку выбора сервера вправо

**Comment by vvzvlad** [comment]
Работает
