### ISSUE TITLE
Меню выбора сервера 

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#40]
1)Сделать так, чтобы snackbar на страницах(ищется в коде по "snackbar") показывался не перекрывая кнопку выбора IP-адреса, а ниже строки меню.
2)Сделать возможность выбора http/https протокола на странице настроек(settings), ну и сохранения всего этого. 
3)Сделать так, чтобы последние пять адресов сервера(http/https, IP, порт) сохранялись в localstorage и кнопка выбора адреса сервера(в верхнем меню) выводила их список

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал все 3 пункта, залил в новый PR #41

**Comment by vvzvlad** [comment]
Вылезает
![image](https://user-images.githubusercontent.com/3315944/43072449-cb496c82-8e7e-11e8-979f-80c6d996bf87.png)

**Comment by nismangulov** [comment]
@vvzvlad 

Поправил ширину колонки, теперь не вылезает

**Comment by vvzvlad** [comment]
Работает
