### ISSUE TITLE
Зависание страницы при загрузке bus

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#43]
Если открыть страницу bus, то где-то 2-3 секунды значений в табличке не появляется, и в это время переход на другую страницу не работает, страница зависает. На других страницах такого нет: logs грузятся мгновенно. Надо как-то починить. Вот пример json. 
[system_bus_data.json.txt](https://github.com/vvzvlad/glue_web_app/files/2219111/system_bus_data.json.txt)

**Comment by nismangulov** [comment]
@vvzvlad 

Долго не мог понять в чём дело, но проблема оказалась не в нашем коде. Оказалось, что в vuetify тормозит рендеринг кнопок. Тормозит рендеринг той пары кнопок, которые находятся в крайнем правом столбце

![image](https://user-images.githubusercontent.com/6184888/43117854-d52e9f44-8f30-11e8-8246-9dffaf85fc20.png)

Пришлось выкинуть v-btn и v-icon, вставил вместо них статичный html - страничка начала открываться практически мгновенно.

**Comment by nismangulov** [comment]
Залил еще один коммит - вынес кнопки в отдельные компоненты, чтобы не захламлять bus.vue

**Comment by vvzvlad** [comment]
О как. А теперь #10 не будет проще сделать?

**Comment by nismangulov** [comment]
@vvzvlad 

Давай попробуем, может сейчас будет проще найти решение
