### ISSUE TITLE
Объединить settings и controls в одну страницу manage

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#44]
Сделать так, чтобы и настройки сервера и кнопки управления были на одной странице. 
Кнопки из controls расположить на отдельной секции controls.

**Comment by nismangulov** [comment]
@vvzvlad 

Перенёс settings и controls на одну страничку с названием manage, залил в новый PR #48

**Comment by vvzvlad** [comment]
Работает.
