### ISSUE TITLE
Подтверждение при нажатии кнопки "Wipe storage and stop" в controls

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#45]
При нажатии кнопки должно появляться всплывающее окно с двумя кнопками "wipe" и "cancel". Команда должна отправляться только при нажатии wipe

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал модалку с подтверждением, залил в #48

**Comment by vvzvlad** [comment]
А можешь тоже в отдельный компонент, как snackbar.vue?

**Comment by nismangulov** [comment]
@vvzvlad 

Аналогично соседнему ишью - вынес модалки в отдельные компоненты, залил в #49

**Comment by vvzvlad** [comment]
Работает, дальнейшее обсуждение в том ишью.
