### ISSUE TITLE
Окно с результатом обновления в controls

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#46]
После нажатия кнопки "update glue" на сервер уходит команда обновления, а сервер возвращает в ответ json, где в response.data.msg находится результат обновления. Результат может быть длинным и многострочным. Надо показывать всплывающее окно, в котором будет этот результат, закрываемое кнопкой.

**Comment by nismangulov** [comment]
@vvzvlad 

Залил в PR #48. Проверить модалку у себя, к сожалению, не на чем, поэтому посмотри плиз у себя, нормально ли работает с бекендом.

**Comment by vvzvlad** [comment]
Работает. А вынеси, пожалуйста, в отдельный компонент, по образцу snackbar.vue?

**Comment by nismangulov** [comment]
@vvzvlad 

Вынес модалки в отдельные компоненты, залил в #49

**Comment by vvzvlad** [comment]
А в чем минус подхода "выносим метод во внешний компонент", как сделано в snackbar.vue, что ты его не стал использовать? 
Там просто получается очень красиво и обособленно — мы говорим "покажи окно с этим текстом", и все, дальше своим состоянием управляет сам компонент. А сейчас логика компонента лежит в основном файле.

**Comment by nismangulov** [comment]
@vvzvlad 

Снекбар был простым компонентом - он только отображал текст, не дёргал никаких функций самостоятельно. Модалку ответа сервера можно переписать, с ней все будет ок, но модалка подтверждения дергает разные функции и придется либо хендлеры держать где-то снаружи, либо дублировать код внутри модалки - что плохо.

**Comment by vvzvlad** [comment]
@nismangulov А зачем дублировать? Засунуть запрос внутрь модалки и пусть она его делает при нажатии ок. А на основной странице просто дергать функцию "вызвать окно"

**Comment by vvzvlad** [comment]
Ну и мне кажется, что даже `<modal @cancel="cancel()" @wipe="wipe()" ></modal>`, когда управлением состоянием находится внутри компонента, а функции лежат снаружи, все равно читабельнее и удобнее, чем когда состояние находится вне компонента.

**Comment by nismangulov** [comment]
@vvzvlad 

Давай тогда переделаю :) это не принципиальный момент

**Comment by vvzvlad** [comment]
Ок. Мне было просто интересно, может это как-то принципиально неверно. Тогда сделай так, чтобы функции компонентов, в том числе, общение с сетью, находились всегда в самом компоненте.

**Comment by nismangulov** [comment]
@vvzvlad 

Переделал модалки, залил в #58

**Comment by vvzvlad** [comment]
С сервера приходит с "/n" переносами строк, а html хочет теги. Сделай так, чтобы переносы срок показывались корректно?
![image](https://user-images.githubusercontent.com/3315944/43245496-22416d16-90b7-11e8-9655-10325ff0757b.png)

**Comment by nismangulov** [comment]
@vvzvlad 

Добавил конвертацию переноса строк, теперь должно быть ок

**Comment by vvzvlad** [comment]
Да, ок. 
Только теперь эта функция используется в двух местах, в /components/logrowdetails.vue и в components/modals/server-response-modal.vue
Вынеси ее куда-нибудь, чтобы не было дублирования кода?

**Comment by nismangulov** [comment]
@vvzvlad 

Вынес функцию `nl2br` в `utils/index.js`. В компонентах её пришлось оборачивать в дополнительную функцию `format_text(text)`, потому что напрямую использовать её в шаблонах нельзя, насколько я понял. Залил в https://github.com/vvzvlad/glue_web_app/pull/70

**Comment by vvzvlad** [comment]
Ага, ок. Разноси только совсем разную функциональность по разным PR в следующий раз, хорошо? Когда они в одном, гораздо труднее читать их.
