### ISSUE TITLE
Окно лога в editor.vue

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#51]
В editor.vue сделать скрываемую/раскрываемую табличку с логами(аналогично табличке в script_details.vue) конкретного скрипта. Как получить логи конкретного скрипта — там же, в script_details.vue есть.

**Comment by vvzvlad** [comment]
@nismangulov Ага. Забыл написать.

**Comment by nismangulov** [comment]
@vvzvlad 

Добавил блок с логами в https://github.com/vvzvlad/glue_web_app/pull/67.

Автообновление логов по таймеру пока не делал (нужно?), но логи запрашиваются заново при каждом закрытии/раскрытии блока.

**Comment by vvzvlad** [comment]
Да, надо:
1)Обновление логов по таймеру(каждую секунду)
2)Открывающаяся карточка должна умещаться на один экран с редактором, т.е. уменьшать размер редактора
3)Размер шрифта логов надо сделать меньше
4)Кнопку "show logs" надо разместить в верхнем баре, там где back, save, reload  и так далее. 
5)Показывать логи автоматически при нажатии "reload script"

**Comment by nismangulov** [comment]
@vvzvlad 

> 1)Обновление логов по таймеру(каждую секунду)

Сделал. Логи обновляются раз в секунду, если окно с логами открыто, если закрыто - таймер останавливается.

> 2)Открывающаяся карточка должна умещаться на один экран с редактором, т.е. уменьшать размер редактора

Сделал автоматический расчет высоты редактора, чтобы всё влезало на один экран.

> 3)Размер шрифта логов надо сделать меньше

А до какого размера? Было 13px с высотой строки 25px, уменьшил до 11px и высоту строки до 20px, дальше станет слишком мелко, мне кажется.

> 4)Кнопку "show logs" надо разместить в верхнем баре, там где back, save, reload и так далее.

Добавил кнопку.

> 5)Показывать логи автоматически при нажатии "reload script"

Сделал. Логи автоматически открываются при рестарте скрипта. 

Залил в #68. Кстати, для нормальной работы нужно будет сделать `npm install` - я там обновил пакет `vue-timers`, там починили критичный баг с таймерами.

**Comment by vvzvlad** [comment]
Баг: 
Табличка с логами начинает показываться только через секунду, на втором запросе:
![image](https://user-images.githubusercontent.com/3315944/43394892-dce97adc-9404-11e8-8499-9ee579eb214b.png)
После первого запроса и до второго она выглядит так:
![image](https://user-images.githubusercontent.com/3315944/43394937-02421adc-9405-11e8-8a8d-bdf0c7f166f3.png)

**Comment by vvzvlad** [comment]
1)По-умолчанию показывать окно логов. Запоминать статус(открыто/закрыто) в localstorage единое для всех скриптов 
2)Размер шрифта ок. Размер самой таблички сделать таким, чтобы влезало 6 строчек. А сложно будет сделать динамическим, чтобы можно было менять размер логов/редакторы мышкой? 
3)Включить паджинацию для этой таблички.

**Comment by vvzvlad** [comment]
Баг: если скрипт длинный, то он не пролистывается до конца, когда лог открыт. Редактор считает, что его размер по-прежнему равен размеру редактора без окна лога.
![image](https://user-images.githubusercontent.com/3315944/43410298-1596ded6-942f-11e8-9d43-e668fac5bd1c.png)

**Comment by nismangulov** [comment]
@vvzvlad 

> Табличка с логами начинает показываться только через секунду, на втором запросе:

Сделал расчет высоты блока логов хитрее, теперь показывается сразу.

> По-умолчанию показывать окно логов. Запоминать статус(открыто/закрыто) в localstorage единое для всех скриптов

Сделал, текущее значение пишется в localstorage, а при открытии редактора - читается из localstorage.

> Размер шрифта ок. Размер самой таблички сделать таким, чтобы влезало 6 строчек. 

Уменьшил размер странички до 6 строк.

> А сложно будет сделать динамическим, чтобы можно было менять размер логов/редакторы мышкой?

Если нужно тянуть мышкой - то долго, можно зависнуть с задачей на пару часов. Если побыстрее - можно добавить в правый верхний угол таблички две кнопки, по которым будем добавлять/уменьшать размер лога на 1 строку

![image](https://user-images.githubusercontent.com/6184888/43437197-866644d8-94a9-11e8-8d03-edcfb27bb8cd.png)

> Включить паджинацию для этой таблички.

Добавил пагинацию под таблицей, поставил в запросе логов лимит на 60 записей

> Баг: если скрипт длинный, то он не пролистывается до конца, когда лог открыт. Редактор считает, что его размер по-прежнему равен размеру редактора без окна лога.

Оказалось багом редактора, он не умеет нормально автоматически обрабатывать изменение высоты. Пришлось делать костыль - триггерить ресайз окна при изменении высоты редактора, вроде помогает.

Залил все в https://github.com/vvzvlad/glue_web_app/pull/70

**Comment by vvzvlad** [comment]
>>По-умолчанию показывать окно логов. Запоминать статус(открыто/закрыто) в localstorage единое для всех скриптов
А по умолчанию не показывается. 

>>Добавил пагинацию под таблицей, поставил в запросе логов лимит на 60 записей
А можешь сделать так, чтобы она была не такой огромной? В user_app делали что-то подобное вроде, чтобы паджинация была размером со строку таблицы.

**Comment by nismangulov** [comment]
> А по умолчанию не показывается.

Поправил дефолтное значение, если в localstorage параметра нет - логи отображаются, если уже есть - используется его значение.

> А можешь сделать так, чтобы она была не такой огромной? В user_app делали что-то подобное вроде, чтобы паджинация была размером со строку таблицы.

Не, мы там поставили такую же пагинацию, но оставили стили по-умолчанию. Она там должна была остаться большой.
Здесь набросал стили, немного ужал пагинацию в размерах - теперь должно быть лучше.

![image](https://user-images.githubusercontent.com/6184888/43499571-096af31e-956e-11e8-9d2e-f43598e471e0.png)

Обновления залил в https://github.com/vvzvlad/glue_web_app/pull/71

**Comment by vvzvlad** [comment]
>можно добавить в правый верхний угол таблички две кнопки, по которым будем добавлять/уменьшать размер лога на 1 строку

Да, вариант нравится, давай так сделаем. 
Только, а) кнопки изменения размера таблицы логов переместить в верхний бар("1" на картинке), б)паджинацию переместить на пустое место в таблице в виде двух кнопок перемещения по страницам и номера текущей страницы, нечего ей место занимать("2" на картинке)

<img width="1440" alt="2" src="https://user-images.githubusercontent.com/3315944/43597772-bd1acae2-968b-11e8-839b-22d9f85233ae.png">

**Comment by nismangulov** [comment]
@vvzvlad 

Перенес пагинацию и добавил кнопки управления размерами лога в https://github.com/vvzvlad/glue_web_app/pull/74

**Comment by vvzvlad** [comment]
А пусть размер окна лога тоже сохраняется в LS?

**Comment by nismangulov** [comment]
@vvzvlad 

сделал. если параметра в LS ещё нет - показывается 6 строк, если есть - будет использоваться тот, что в LS

https://github.com/vvzvlad/glue_web_app/pull/75

**Comment by vvzvlad** [comment]
Работает
