### ISSUE TITLE
Кнопка "подробности записи" в logs.vue и в files_table.vue

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#53]
Сейчас подробности показываются при нажатии на строку, надо сделать так, чтобы показывались по нажатию на кнопку. Кнопка в каждой строке, аналогично bus. 
Тоже самое в files_table.vue.

**Comment by vvzvlad** [comment]
Круто, работает.

**Comment by vvzvlad** [comment]
![image](https://user-images.githubusercontent.com/3315944/43245373-bd85f0b8-90b6-11e8-9f5d-58ac57239f62.png)
Поехало

**Comment by nismangulov** [comment]
@vvzvlad 

Влад, а ты на мастере тестил после мержа? У меня такое тоже один раз вылезло один раз, но пропало и я даже понять не успел, в чем была проблема. Сейчас вроде ок 

![image](https://user-images.githubusercontent.com/6184888/43245599-b6be9ebe-90d0-11e8-803e-ea9553d177d7.png)

**Comment by vvzvlad** [comment]
Вроде больше не появляется.
