### ISSUE TITLE
Вопрос "точно выйти" при выходе без сохранения в editor.vue

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#55]
Если текущий текст был изменен со времени последней загрузки или сохранения, то перед выходом спрашивать "точно выйти, у вас несохраненные данные?". 
Как я понял, надо использовать beforeRouteLeave из https://router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards

**Comment by nismangulov** [comment]
@vvzvlad 

> Как я понял, надо использовать beforeRouteLeave

Почти. Есть два кейса - при смене текущего урла страницы и при закрытии вкладки. `beforeRouteLeave` сработает только в первом кейсе, для закрытия вкладки нужно использовать `window.onbeforeunload`

Сейчас залил код в #64, но решение пока частичное - подтверждение ложно срабатывает на загрузку файла и сбрасывает флаг `saved`, хотя не должно. Нужно подумать, как его красиво обхитрить.

**Comment by vvzvlad** [comment]
На закрытие вкладки можно не реагировать.

**Comment by vvzvlad** [comment]
Кейс: открываем скрипт, ничего не трогаем в редакторе, нажимаем "back", всплывает окно с подтверждением. Это ты про это говорил?

**Comment by nismangulov** [comment]
@vvzvlad 

Залил апдейт, теперь вроде всё корректно определяется

**Comment by vvzvlad** [comment]
Неправильное поведение. Кейс:
Ставим курсор в любое место файла, вводим символ, курсор прыгает в конец файла. Необходимо, чтобы он оставался на месте.

**Comment by vvzvlad** [comment]
Вопрос о сохранении работает корректно.

**Comment by nismangulov** [comment]
@vvzvlad 

Курсор починил, залил вместе с соседним ишью в #68

**Comment by vvzvlad** [comment]
Вообще перестало работать(

**Comment by nismangulov** [comment]
@vvzvlad 

Оживил https://github.com/vvzvlad/glue_web_app/pull/69

**Comment by vvzvlad** [comment]
Да, вроде ок.
