### ISSUE TITLE
Механизм передачи содержимого файлов из/в editor.vue

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#56]
Сейчас там ужас и мрак, файл передается в строке адреса в base64, из-за чего есть ограничения по длине файла для сохранения, что грустно и больше. Но это единственный способ, который я нашел, чтобы содержимое файла не билось. Как это сделать правильно?

**Comment by nismangulov** [comment]
@vvzvlad

**Comment by nismangulov** [comment]
@vvzvlad 

Верно, у HTTP GET запросов есть ограничение в 2048 символов. По-хорошему, такие вещи нужно слать через POST, с ним и base64 не нужен будет.

**Comment by nismangulov** [comment]
@vvzvlad 

Залил в https://github.com/vvzvlad/glue_web_app/pull/66. По-умолчанию axios шлёт данные через json, я пока не стал менять это.

> там иногда возникают какие-то проблемы с символами в коде

А не помнишь на каких? По идее, json без экранирования символов может ломаться на кавычках. Можно на клиенте содержимое файла перед передачей заворачивать в base64 или https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent, а на сервере перед сохранением - разворачивать обратно.
