### ISSUE TITLE
Переносы строк в логах и шине

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#6]
В bus storage и logs(файлы logs.vue и bus.vue) есть таблица. Необходимо: 
1)Зафиксировать высоту строки на уровне высоты строки текста. 
2)Если текст в ячейке таблицы больше, чем текущая ширина ячейки(она динамическая, задается в процентах от общей ширины таблицы), то он должен обрезаться, а не переноситься на следующую строку. Конец обрезанной строки дополняется тремя точками.
3)Желательно сделать это средствами html/css(т.е. overflow: hidden, text-overflow: ellipsis и так далее)
4)Обрезанная строка показывается при наведении на нее мышкой(title)

Пример переноса строки: 
<img width="1265" alt="screen 2018-06-05 18 18 01" src="https://user-images.githubusercontent.com/3315944/40991824-a64abc66-68fd-11e8-86c9-c6aa7a5c4205.png">

**Comment by vvzvlad** [comment]
[system_bus_data.json.txt](https://github.com/vvzvlad/glue_web_app/files/2075572/system_bus_data.json.txt)
[system_logger_action.json.txt](https://github.com/vvzvlad/glue_web_app/files/2075573/system_logger_action.json.txt)

**Comment by nismangulov** [comment]
@vvzvlad сделал, создал PR #7

**Comment by vvzvlad** [comment]
102 минуты, 2380 рублей.
