### ISSUE TITLE
Сокращение отступов

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#73]
Огромная куча полезного пространства тратится на отступы. Надо их как-то сократить. См. картинку.
<img width="1440" alt="1" src="https://user-images.githubusercontent.com/3315944/43597942-304e0d62-968c-11e8-9069-219e4bb2ef6d.png">

**Comment by nismangulov** [comment]
Немного ужал размеры, стало лучше. Залил в https://github.com/vvzvlad/glue_web_app/pull/74

![image](https://user-images.githubusercontent.com/6184888/43637616-7df834f6-9737-11e8-8dda-d0f573a8eb5f.png)

**Comment by vvzvlad** [comment]
Да, хорошо. А делай в следующий раз разные PR по разным ишью?
