### ISSUE TITLE
Кнопка "help" в editor.vue

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#79]
Сделать кнопку "help", по нажатию которой будет показываться модальное окно с текстом. Текст заполню сам.

**Comment by nismangulov** [comment]
Добавил отдельный компонент с модалкой и добавил кнопку для её вызова в `editor.vue`, залил в https://github.com/vvzvlad/glue_web_app/pull/84

**Comment by vvzvlad** [comment]
работает
