### ISSUE TITLE
Версия бекенда и фронтенда

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#80]
В самом низу колонки меню добавить версию бекенда и фронтенда:

```
GLUE: v0.6-7-gfccf97b
GApp: v0.6-2-g5194fc3
2018 © Nokia IoT Laboratory
```

Версию фронтенда получать при сборке командой `git describe --dirty --always --tags`, версию бекенда — запросом "system_event?action=get_git_version" из переменной data.version.

**Comment by vvzvlad** [comment]
Работает. Ему npm install надо было сделать?

**Comment by nismangulov** [comment]
@vvzvlad 

Да, нужно. Там добавился новый плагин для вебпака, для работы с `git describe`.
