### ISSUE TITLE
Настройки экспорта в Manage

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#88]
Создать в Manage еще один раздел, в котором разместить две галочки: "Save to Influx" и "Send to Impact". При снятии или установке галочки запрос на изменение должен отправляться на сервер. Статус запрашивается с сервера при открытии страницы
Запросы для установки: "export?action=set&type=influx&status=true" и "export?action=set&type=impact&status=false"
Запросы для получения текущего статуса: "export?action=get&type=influx" и "export?action=get&type=impact" (поле data.status, тип boolean)

**Comment by nismangulov** [comment]
@vvzvlad 

Набросал изменение флагов, залил в https://github.com/vvzvlad/glue_web_app/pull/93

Но есть проблема - я не могу запустить последнюю версию бекенда, где этот экспорт был реализован, пока работу с апи делал вслепую.

Последняя версия падает с ошибкой, что не может найти модуль `mqtt` https://gist.github.com/nismangulov/e3206674395a623d5b25b67879e8a7d8, пытаюсь установить `mqtt` - падает с ошибкой, что не может найти `libmosquitto` https://gist.github.com/nismangulov/bc2e2973d257e72c65df1ce292163b10. Поставил пакет `mosquitto` через `brew` - не помогает, библиотеку все равно не находит. Может там какая-то особенная магия ещё нужна? Можешь подсказать?

**Comment by vvzvlad** [comment]
А он там еще не реализован, я допишу сегодня и сам поправлю, если что не так. 

По поводу mqtt — странно. У меня вот так в том месте, где он падает: 
```
-- Found MOSQUITTO: /usr/local/lib/libmosquitto.dylib  
-- libmosquitto include dir: /usr/local/include
```
У тебя в этой папке он есть?

**Comment by vvzvlad** [comment]
А можешь вынести это в отдельный компонент?

**Comment by nismangulov** [comment]
@vvzvlad 

> А он там еще не реализован, я допишу сегодня и сам поправлю, если что не так.

Тогда ок - вынес в отдельный компонент, залил в #93 

> По поводу mqtt — странно. У меня вот так в том месте, где он падает:

Починил - у меня `brew` почему-то сломался и `mosquitto` не ставился до конца. Теперь починил его, все ставится ок.

**Comment by vvzvlad** [comment]
>(поле data.status, тип boolean)

Просил status, а было value. Поправил в бекенде, value и правда лучше описывает. Но ты в следующий раз говори, пожалуйста, если что-то меняешь. 

Также, при загрузке зачем-то делается set. 
![image](https://user-images.githubusercontent.com/3315944/43833051-177622ea-9b12-11e8-8139-624a9a316dce.png)

**Comment by nismangulov** [comment]
@vvzvlad 

>Просил status, а было value. Поправил в бекенде, value и правда лучше описывает. Но ты в следующий раз говори, пожалуйста, если что-то меняешь.

Это был мой косяк. Я тогда не заметил.

> Также, при загрузке зачем-то делается set.

Переписал и упростил логику, больше set не должен зря вызываться. Залил в #98

**Comment by vvzvlad** [comment]
работает
