### ISSUE TITLE
Между столбцами в таблице большие промежутки

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#90]
![image](https://user-images.githubusercontent.com/3315944/43795866-48bd9090-9a8b-11e8-86e3-ede6941ce99a.png)
Между "value" и "type" очень большой промежуток, хотя в верстке они прижаты к правому и левому краю. Это промежуток между любыми столбцами? Он крадет кучу места. Его можно сделать в раза 4-5 меньше.

**Comment by nismangulov** [comment]
@vvzvlad 

Уменьшил паддинги с 24px с обоих сторон до 4px. Залил в https://github.com/vvzvlad/glue_web_app/pull/95

Ещё у последних двух столбцов (update time, actions) сделал ширину статичной вместо динамической - на больших экранах должно красть меньше места.

**Comment by vvzvlad** [comment]
работает.
