### ISSUE TITLE
Редактирование топика в BUS

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#91]
![image](https://user-images.githubusercontent.com/3315944/43795962-88211612-9a8b-11e8-9331-cb82ac05eb0a.png)
![image](https://user-images.githubusercontent.com/3315944/43795966-8bd35d7e-9a8b-11e8-8b47-f3d265a9779a.png)
При нажатии edit меняется размер поля. Давай его сразу сделаем полем для ввода, просто пока не нажата кнопка edit, оно не будет доступно для ввода?

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал отключенные инпуты с текстом, а по кнопке изменения - поле становится доступным для ввода. Залил в #99

**Comment by vvzvlad** [comment]
Работает
