### ISSUE TITLE
"No data available" в таблицах

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_web_app#92]
![image](https://user-images.githubusercontent.com/3315944/43796037-bf62dfc0-9a8b-11e8-820b-6de883b7a6ef.png)
Если данные пришли, но там ничего нет, не надо говорить "No data available", надо сказать "No scripts" в files_table, "no log entries" в логе, "No bus topics" в bus, и "No backups" в бекапах.

**Comment by nismangulov** [comment]
@vvzvlad 

Залил в #102.

Сделал такую логику - если данных ещё нет или с бекенда пришла ошибка - выводится пустая табличка с надписью "No data available". Если же данные с бекенда удачно пришли, но пустые - выводится уже нужная надпись, в зависимости от раздела.

**Comment by vvzvlad** [comment]
Работает
